services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    build:
      target: dev
    environment:
      CERT_FILE: /app/certs/cert.pem
      KEY_FILE: /app/certs/key.pem
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_SECRET: ${MERCURE_PUBLISHER_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_SECRET: ${MERCURE_SUBSCRIBER_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: ${DATABASE_URL}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${MERCURE_PUBLIC_URL:-https://localhost/.well-known/mercure}
      MERCURE_TRANSPORT_URL: ${MERCURE_TRANSPORT_URL:-redis://redis:6379/1}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:-https://localhost}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    depends_on:
      - database
      - redis
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./templates:/app/templates
      - ./assets:/app/assets
      - ./public:/app/public
      - ./webpack.config.js:/app/webpack.config.js
      - ./package.json:/app/package.json
      - ${SSL_CERT_PATH}:/app/certs/cert.pem:ro
      - ${SSL_KEY_PATH}:/app/certs/key.pem:ro
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    networks:
      - app_network

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app_network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  messenger-scheduler:
    image: ${IMAGES_PREFIX:-}app-php
    build:
      target: frankenphp_dev
    restart: unless-stopped
    command: php bin/console messenger:consume scheduler_default -vv
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_ADMIN_CHAT_ID: ${TELEGRAM_ADMIN_CHAT_ID}
    depends_on:
      - database
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - app_network

  messenger-worker:
    image: ${IMAGES_PREFIX:-}app-php
    build:
      target: frankenphp_dev
    restart: unless-stopped
    command: php bin/console messenger:consume scheduled_queue default_queue auth_queue -vv
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_ADMIN_CHAT_ID: ${TELEGRAM_ADMIN_CHAT_ID}
    depends_on:
      - database
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - app_network
volumes:
  caddy_data:
  caddy_config:
  redis_data:
###> symfony/mercure-bundle ###
  elasticsearch_data:
  rabbitmq_data:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
###< symfony/mercure-bundle ###
networks:
  app_network:
    driver: bridge

