<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250130005048 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bookings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, time_start TIME(0) WITHOUT TIME ZONE NOT NULL, time_stop TIME(0) WITHOUT TIME ZONE NOT NULL, id_master_id INT NOT NULL, pet_id INT NOT NULL, id_client_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7A853C3593866736 ON bookings (id_master_id)');
        $this->addSql('CREATE INDEX IDX_7A853C35966F7FB6 ON bookings (pet_id)');
        $this->addSql('CREATE INDEX IDX_7A853C3599DED506 ON bookings (id_client_id)');
        $this->addSql('CREATE TABLE bookings_services (bookings_id INT NOT NULL, services_id INT NOT NULL, PRIMARY KEY(bookings_id, services_id))');
        $this->addSql('CREATE INDEX IDX_9BA18C54AAC0EC61 ON bookings_services (bookings_id)');
        $this->addSql('CREATE INDEX IDX_9BA18C54AEF5A6C1 ON bookings_services (services_id)');
        $this->addSql('CREATE TABLE cities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE clients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE clients_pets (clients_id INT NOT NULL, pets_id INT NOT NULL, PRIMARY KEY(clients_id, pets_id))');
        $this->addSql('CREATE INDEX IDX_81EC3DEAB014612 ON clients_pets (clients_id)');
        $this->addSql('CREATE INDEX IDX_81EC3DEC5E5C4E3 ON clients_pets (pets_id)');
        $this->addSql('CREATE TABLE masters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, id_city_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7493B1495531CBDF ON masters (id_city_id)');
        $this->addSql('CREATE TABLE masters_services (masters_id INT NOT NULL, services_id INT NOT NULL, PRIMARY KEY(masters_id, services_id))');
        $this->addSql('CREATE INDEX IDX_7B0CE41A8DD22E0C ON masters_services (masters_id)');
        $this->addSql('CREATE INDEX IDX_7B0CE41AAEF5A6C1 ON masters_services (services_id)');
        $this->addSql('CREATE TABLE masters_pets (masters_id INT NOT NULL, pets_id INT NOT NULL, PRIMARY KEY(masters_id, pets_id))');
        $this->addSql('CREATE INDEX IDX_9F3633B88DD22E0C ON masters_pets (masters_id)');
        $this->addSql('CREATE INDEX IDX_9F3633B8C5E5C4E3 ON masters_pets (pets_id)');
        $this->addSql('CREATE TABLE pets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spice VARCHAR(255) NOT NULL, hair VARCHAR(255) NOT NULL, breed VARCHAR(255) NOT NULL, size VARCHAR(255) NOT NULL, cost_coficient DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_ofweek VARCHAR(255) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, stop_time TIME(0) WITHOUT TIME ZONE NOT NULL, master_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5A3811FB13B3DB11 ON schedule (master_id)');
        $this->addSql('CREATE TABLE services (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, cost INT NOT NULL, default_time TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE bookings ADD CONSTRAINT FK_7A853C3593866736 FOREIGN KEY (id_master_id) REFERENCES masters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bookings ADD CONSTRAINT FK_7A853C35966F7FB6 FOREIGN KEY (pet_id) REFERENCES pets (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bookings ADD CONSTRAINT FK_7A853C3599DED506 FOREIGN KEY (id_client_id) REFERENCES clients (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bookings_services ADD CONSTRAINT FK_9BA18C54AAC0EC61 FOREIGN KEY (bookings_id) REFERENCES bookings (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bookings_services ADD CONSTRAINT FK_9BA18C54AEF5A6C1 FOREIGN KEY (services_id) REFERENCES services (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE clients_pets ADD CONSTRAINT FK_81EC3DEAB014612 FOREIGN KEY (clients_id) REFERENCES clients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE clients_pets ADD CONSTRAINT FK_81EC3DEC5E5C4E3 FOREIGN KEY (pets_id) REFERENCES pets (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE masters ADD CONSTRAINT FK_7493B1495531CBDF FOREIGN KEY (id_city_id) REFERENCES cities (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE masters_services ADD CONSTRAINT FK_7B0CE41A8DD22E0C FOREIGN KEY (masters_id) REFERENCES masters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE masters_services ADD CONSTRAINT FK_7B0CE41AAEF5A6C1 FOREIGN KEY (services_id) REFERENCES services (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE masters_pets ADD CONSTRAINT FK_9F3633B88DD22E0C FOREIGN KEY (masters_id) REFERENCES masters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE masters_pets ADD CONSTRAINT FK_9F3633B8C5E5C4E3 FOREIGN KEY (pets_id) REFERENCES pets (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB13B3DB11 FOREIGN KEY (master_id) REFERENCES masters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bookings DROP CONSTRAINT FK_7A853C3593866736');
        $this->addSql('ALTER TABLE bookings DROP CONSTRAINT FK_7A853C35966F7FB6');
        $this->addSql('ALTER TABLE bookings DROP CONSTRAINT FK_7A853C3599DED506');
        $this->addSql('ALTER TABLE bookings_services DROP CONSTRAINT FK_9BA18C54AAC0EC61');
        $this->addSql('ALTER TABLE bookings_services DROP CONSTRAINT FK_9BA18C54AEF5A6C1');
        $this->addSql('ALTER TABLE clients_pets DROP CONSTRAINT FK_81EC3DEAB014612');
        $this->addSql('ALTER TABLE clients_pets DROP CONSTRAINT FK_81EC3DEC5E5C4E3');
        $this->addSql('ALTER TABLE masters DROP CONSTRAINT FK_7493B1495531CBDF');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT FK_7B0CE41A8DD22E0C');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT FK_7B0CE41AAEF5A6C1');
        $this->addSql('ALTER TABLE masters_pets DROP CONSTRAINT FK_9F3633B88DD22E0C');
        $this->addSql('ALTER TABLE masters_pets DROP CONSTRAINT FK_9F3633B8C5E5C4E3');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB13B3DB11');
        $this->addSql('DROP TABLE bookings');
        $this->addSql('DROP TABLE bookings_services');
        $this->addSql('DROP TABLE cities');
        $this->addSql('DROP TABLE clients');
        $this->addSql('DROP TABLE clients_pets');
        $this->addSql('DROP TABLE masters');
        $this->addSql('DROP TABLE masters_services');
        $this->addSql('DROP TABLE masters_pets');
        $this->addSql('DROP TABLE pets');
        $this->addSql('DROP TABLE schedule');
        $this->addSql('DROP TABLE services');
    }
}
