<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250823031047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE districts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, city_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_68E318DC8BAC62AF ON districts (city_id)');
        $this->addSql('ALTER TABLE districts ADD CONSTRAINT FK_68E318DC8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D95DB16B2D5B0234 ON cities (city)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82E74E7927C74 ON clients (email)');
        $this->addSql('ALTER TABLE masters ADD avg_rating DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql("ALTER TABLE masters ADD address VARCHAR(255) NOT NULL DEFAULT 'Unknown'");
        $this->addSql('ALTER TABLE masters ADD district_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE masters ADD CONSTRAINT FK_7493B149B08FA272 FOREIGN KEY (district_id) REFERENCES districts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_7493B149B08FA272 ON masters (district_id)');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT fk_7b0ce41a8dd22e0c');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT fk_7b0ce41aaef5a6c1');
        $this->addSql('DROP INDEX idx_7b0ce41aaef5a6c1');
        $this->addSql('DROP INDEX idx_7b0ce41a8dd22e0c');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT masters_services_pkey');
        $this->addSql('ALTER TABLE masters_services ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY');
        $this->addSql('ALTER TABLE masters_services ADD price DOUBLE PRECISION');
        $this->addSql('UPDATE masters_services ms SET price = s.cost FROM services s WHERE ms.services_id = s.id');
        $this->addSql('ALTER TABLE masters_services ADD master_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE masters_services ADD service_id INT DEFAULT NULL');
        $this->addSql('UPDATE masters_services SET master_id = masters_id, service_id = services_id');
        $this->addSql('ALTER TABLE masters_services DROP masters_id');
        $this->addSql('ALTER TABLE masters_services DROP services_id');
        $this->addSql('ALTER TABLE masters_services ALTER COLUMN price SET NOT NULL');
        $this->addSql('ALTER TABLE masters_services ALTER COLUMN master_id SET NOT NULL');
        $this->addSql('ALTER TABLE masters_services ALTER COLUMN service_id SET NOT NULL');
        $this->addSql('ALTER TABLE masters_services ADD CONSTRAINT FK_7B0CE41A13B3DB11 FOREIGN KEY (master_id) REFERENCES masters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE masters_services ADD CONSTRAINT FK_7B0CE41AED5CA9E6 FOREIGN KEY (service_id) REFERENCES services (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_7B0CE41A13B3DB11 ON masters_services (master_id)');
        $this->addSql('CREATE INDEX IDX_7B0CE41AED5CA9E6 ON masters_services (service_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE districts DROP CONSTRAINT FK_68E318DC8BAC62AF');
        $this->addSql('DROP TABLE districts');
        $this->addSql('ALTER TABLE masters DROP CONSTRAINT FK_7493B149B08FA272');
        $this->addSql('DROP INDEX IDX_7493B149B08FA272');
        $this->addSql('ALTER TABLE masters DROP avg_rating');
        $this->addSql('ALTER TABLE masters DROP address');
        $this->addSql('ALTER TABLE masters DROP district_id');
        $this->addSql('DROP INDEX UNIQ_D95DB16B2D5B0234');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT FK_7B0CE41A13B3DB11');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT FK_7B0CE41AED5CA9E6');
        $this->addSql('DROP INDEX IDX_7B0CE41A13B3DB11');
        $this->addSql('DROP INDEX IDX_7B0CE41AED5CA9E6');
        $this->addSql('ALTER TABLE masters_services DROP CONSTRAINT masters_services_pkey');
        $this->addSql('ALTER TABLE masters_services ADD masters_id INT NOT NULL');
        $this->addSql('ALTER TABLE masters_services ADD services_id INT NOT NULL');
        $this->addSql('ALTER TABLE masters_services DROP id');
        $this->addSql('ALTER TABLE masters_services DROP price');
        $this->addSql('ALTER TABLE masters_services DROP master_id');
        $this->addSql('ALTER TABLE masters_services DROP service_id');
        $this->addSql('ALTER TABLE masters_services ADD CONSTRAINT fk_7b0ce41a8dd22e0c FOREIGN KEY (masters_id) REFERENCES masters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE masters_services ADD CONSTRAINT fk_7b0ce41aaef5a6c1 FOREIGN KEY (services_id) REFERENCES services (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_7b0ce41aaef5a6c1 ON masters_services (services_id)');
        $this->addSql('CREATE INDEX idx_7b0ce41a8dd22e0c ON masters_services (masters_id)');
        $this->addSql('ALTER TABLE masters_services ADD PRIMARY KEY (masters_id, services_id)');
        $this->addSql('DROP INDEX UNIQ_C82E74E7927C74');
    }
}
